---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bluebuild-niri-nvidia
description: DeVelox's custom BlueBuild image.
base-image: ghcr.io/blue-build/base-images/fedora-base-nvidia-open
image-version: latest
modules:
  - type: dnf
    repos:
      files:
        - https://raw.githubusercontent.com/terrapkg/subatomic-repos/main/terra.repo
    install:
      packages:
        # core
        - niri
        - mako
        - nautilus
        - gnome-keyring
        - xfce-polkit
        - fuse-libs
        # shell
        - fish
        - helix
        - fd-find
        - ripgrep
        - zoxide
        - direnv
        - ugrep
        - wtype
        - ncdu
        - btop
        - bat
        - eza
        # pkgs
        - podlet
        - podman-compose
        - qemu-kvm
        - qemu-img
        - nix-core
