---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bluebuild-niri-nvidia
description: DeVelox's custom BlueBuild image.
base-image: ghcr.io/blue-build/base-images/fedora-base-nvidia-open
image-version: latest
modules:
  - type: script
    snippets:
      - "dnf install -y --nogpgcheck --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' terra-release"
  - type: dnf
    install:
      packages:
        - niri
        - mako
        - nautilus
        - gnome-keyring
        - xfce-polkit
        - fuse-libs
        - alacritty
        - atuin
        - bat
        - btop
        - direnv
        - eza
        - fd-find
        - fish
        - helix
        - ncdu
        - nix-core
        - podlet
        - podman-compose
        - quickemu
        - ripgrep
        - starship
        - ugrep
        - wtype
        - zellij
        - zoxide
